include: package:lint/analysis_options.yaml

linter:
  rules:
    avoid_dynamic_calls: false
    prefer_single_quotes: true
    depend_on_referenced_packages: false
    use_build_context_synchronously: false